# Generated by Django 4.0.3 on 2022-06-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pdf_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='title',
            new_name='დასახელება',
        ),
    ]
