# Generated by Django 4.0.3 on 2022-06-07 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_title_pdf_დასახელება'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='Pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
